Code implementation of - **S. Dua, J. Singh, and H. Parthasarathy, “Image forgery detection based on statistical features of block dct coefficients,” Procedia Computer Science, vol. 171, pp. 369–378, 2020, third International Conference on Computing and Network Communications (CoCoNet’19). [Online]. 
Available: https://www.sciencedirect.com/science/article/pii/S1877050920310048**

In [2]:
import cv2
import pandas as pd
import numpy as np
import os
from scipy.fftpack import fft, dct
from sklearn import svm
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from skimage.util import view_as_windows

In [3]:
def get_patches(image_mat):
    """
    Extract patches rom an image
    :param image_mat: The image as a matrix
    :param stride: The stride of the patch extraction process
    :returns: The patches
    """
    stride=8 #stride is same as window's breadth so that it gives non-overlapping blocks.
    window_shape = (8, 8)
    image_mat=np.array(image_mat)
    
    windows = view_as_windows(image_mat, window_shape, step=stride)
#     print('windows shape:',windows.shape)

    patches = []
    for m in range(windows.shape[0]):
        for n in range(windows.shape[1]):
#             print("window shape: ",windows[m][n].shape)
            patches += [windows[m][n]]
    return patches

In [4]:
def std_and_ones(type_of_sub_image_blocks):
    ac_dct_stack=[]
    number_of_ones=[]

    for block in type_of_sub_image_blocks:
        dct_block = dct(block, type=2, n=None, axis=-1, norm=None, overwrite_x=False)
        dct_block_row = dct_block.flatten() # 2d dct array to 1d row array.
        ac_dct = dct_block_row[1:] # only AC component, removing the first DC comp.
        ac_dct_stack.append(ac_dct)

    ac_dct_stack=np.asarray(ac_dct_stack) #1536X63
    ac_dct_stack=ac_dct_stack.T # 63X1536

#     print("AC stacked shape: ", ac_dct_stack.shape)

    ac_dct_std = np.std(ac_dct_stack, axis=1) # row wise standard-deviation.

    for i in range(ac_dct_stack.shape[0]):
        count_one=0
        for j in range(ac_dct_stack.shape[1]):
            if(ac_dct_stack[i][j]>0):   # row wise counting number of ones.
                count_one+=1
        number_of_ones.append(count_one)

    number_of_ones=np.asarray(number_of_ones)
    
    return(ac_dct_std, number_of_ones)

In [5]:
def feature_sub_image(sub_image):
    sub_image_blocks = get_patches(sub_image) #Gives the 8x8 patches/blocks of sub_image.

    sub_image_cropped = sub_image[4:,4:] #removing 4 rows and 4 cols.
    sub_image_cropped_blocks = get_patches(sub_image_cropped)

    STD_full_image, ONE_full_image = std_and_ones(sub_image_blocks)
    STD_cropped_image, ONE_cropped_image = std_and_ones(sub_image_cropped_blocks)

    #             print("STD_full image shape: ",STD_full_image.shape)
    #             print("one_full image shape: ",ONE_full_image.shape)
    #             print("STD_crop image shape: ",STD_cropped_image.shape)
    #             print("One_crop image shape: ",ONE_cropped_image.shape)
    
    #63x4 stacked F-sub-image
    F_sub_image=np.column_stack((STD_full_image, ONE_full_image, STD_cropped_image, ONE_cropped_image))
    
    F_sub_image_flat=F_sub_image.T.flatten() #column wise flattening, 63*4=252 features
    return(F_sub_image_flat)

In [6]:
#main function to extract the features.
def feature_extraction(path_to_folder, class_label):
    data_list=[]
    for file_name in os.listdir(path_to_folder):
        path_to_img = os.path.join(path_to_folder,file_name)
        img = cv2.imread(path_to_img)
        
        if np.shape(img) == ():
            continue
        
        img = cv2.cvtColor(img, cv2.COLOR_BGR2YCrCb) #changing to YCrCb color space.
        img_y = img[:,:,0] # the Y channel only.
        img_cr = img[:,:,1] # the Cr channel only.
        img_cb = img[:,:,2] # the Cb channel only.
        
        Fy = feature_sub_image(img_y)
        Fcr = feature_sub_image(img_cr)
        Fcb = feature_sub_image(img_cb)
#         print("fy shape: ",Fy.shape)
#         print("fcr shape: ",Fcr.shape)
#         print("fcb shape: ",Fcb.shape)
        
        final_feature = np.concatenate((Fy, Fcb, Fcr), axis=None) #63*4*3=756 flattened features.
#         print("final feature shape: ",final_feature.shape)
        
        final_feature=list(final_feature)
        final_feature.insert(0,file_name)
        final_feature.insert(1,class_label)
        data_list.append(final_feature)
        
        
    return(data_list)

In [50]:
# #CASIA V1.0 dataset
# au_path = "YOUR_PATH/CASIA 1.0 dataset/Au"
# tp_path1 = "YOUR_PATH/CASIA 1.0 dataset/Modified Tp/Tp/CM"
# tp_path2 = "YOUR_PATH/CASIA 1.0 dataset/Modified Tp/Tp/Sp"
# output_name='CASIA1_features.csv'

# data_list1 = feature_extraction(au_path, 0)
# data_list2 = feature_extraction(tp_path1, 1)
# data_list3 = feature_extraction(tp_path2, 1)

# df = pd.DataFrame(data_list1)
# df = df.append(pd.DataFrame(data_list2), ignore_index=True)
# df = df.append(pd.DataFrame(data_list3), ignore_index=True)
#  --------------------------------------------------------------------------------------

# CASIA V2.0 Dataset
au_path="/kaggle/input/casia-20-image-tampering-detection-dataset/CASIA2/Au"
tp_path="/kaggle/input/casia-20-image-tampering-detection-dataset/CASIA2/Tp"
output_name='CASIA2_features.csv'

data_list1 = feature_extraction(au_path, 0)
data_list2 = feature_extraction(tp_path, 1)

df = pd.DataFrame(data_list1)
df = df.append(pd.DataFrame(data_list2), ignore_index=True)

#  --------------------------------------------------------------------------------------

# Keep this as it is
df.rename(columns = {0: "image_names", 1: "label"}, inplace = True)

scaler_norm = MinMaxScaler(feature_range=(0, 1), *, copy=True, clip=False) 
df.iloc[:,2:] = scaler_norm.fit_transform(df.iloc[:,2:].to_numpy()) # Normalising the values in dataframe.

df.to_csv(output_name, index=False)

In [51]:
df.shape

(12614, 758)

## SVM CLASSIFICATION CASIA 2.0

In [7]:
df=pd.read_csv('/Users/andre/Desktop/conda/grad/CASIA3_features.csv')
df

image_names  label         2         3         4         5  \
0      Au_pla_30322.jpg      0  0.203030  0.114708  0.091051  0.071826   
1      Au_ani_10197.jpg      0  0.153429  0.099287  0.123705  0.130321   
2      Au_nat_00098.jpg      0  0.075379  0.058618  0.055116  0.050434   
3      Au_nat_30407.jpg      0  0.320666  0.322521  0.298455  0.272717   
4      Au_arc_20034.jpg      0  0.298256  0.227842  0.216022  0.196337   
...                 ...    ...       ...       ...       ...       ...   
14330   Au_txt_0096.jpg      0  0.737459  0.788444  0.730644  0.605657   
14331   Au_txt_0097.jpg      0  0.365549  0.491332  0.494500  0.448025   
14332   Au_txt_0098.jpg      0  0.229045  0.217076  0.171976  0.127476   
14333   Au_txt_0099.jpg      0  0.406170  0.497929  0.483714  0.448247   
14334   Au_txt_0100.jpg      0  0.448161  0.543583  0.571043  0.531154   

              6         7         8         9  ...       748       749  \
0      0.061546  0.051228  0.040522  0.381164  ...  0.137913  0.175814   
1      0.138604  0.127693  0.166308  0.380715  ...  0.135115  0.161243   
2      0.045391  0.043785  0.042841  0.510323  ...  0.054707  0.106605   
3      0.269061  0.261953  0.242288  0.416608  ...  0.138931  0.174114   
4      0.181617  0.196589  0.182347  0.488406  ...  0.425445  0.338514   
...         ...       ...       ...       ...  ...       ...       ...   
14330  0.520775  0.621279  0.482222  0.478789  ...  0.422056  0.480904   
14331  0.376877  0.439603  0.321650  0.216863  ...  0.543118  0.539361   
14332  0.077273  0.076050  0.055724  0.403313  ...  0.417910  0.477007   
14333  0.398195  0.450239  0.341832  0.483110  ...  0.540630  0.632112   
14334  0.508777  0.655226  0.530447  0.402413  ...  0.262023  0.312549   

            750       751       752       753       754       755       756  \
0      0.117100  0.132071  0.121396  0.130337  0.085628  0.153904  0.128289   
1      0.316789  0.230002  0.134294  0.220743  0.041452  0.219506  0.135881   
2      0.117100  0.090954  0.054628  0.088147  0.041755  0.087304  0.060476   
3      0.117100  0.126838  0.129995  0.136364  0.110741  0.141432  0.139423   
4      0.747706  0.544231  0.421345  0.487443  0.247201  0.510352  0.409919   
...         ...       ...       ...       ...       ...       ...       ...   
14330  0.017669  0.398091  0.413878  0.385524  0.300337  0.400253  0.417836   
14331  0.017669  0.408998  0.552653  0.423191  0.607424  0.459151  0.540875   
14332  0.017669  0.423995  0.439184  0.395864  0.429696  0.432552  0.439306   
14333  0.017669  0.439673  0.535510  0.433530  0.525309  0.478784  0.526012   
14334  0.017669  0.292434  0.269388  0.294682  0.105737  0.317923  0.268373   

            757  
0      0.180267  
1      0.163205  
2      0.108803  
3      0.168398  
4      0.336301  
...         ...  
14330  0.446856  
14331  0.501497  
14332  0.493263  
14333  0.588323  
14334  0.330090  

[14335 rows x 758 columns]

In [7]:
newpicst = "/Users/andre/Desktop/conda/grad/tp"
newpicsa = "/Users/andre/Desktop/conda/grad/au"
newimt = feature_extraction(newpicst,1)
newima = feature_extraction(newpicsa,0)
ndf = pd.DataFrame(newimt)
ndf = ndf.append(pd.DataFrame(newima), ignore_index=True)
ndf.rename(columns = {0: "image_names", 1: "label"}, inplace = True)
scaler_norm = MinMaxScaler(feature_range=(0, 1),copy=True, clip=True) 
ndf.iloc[:,2:] = scaler_norm.fit_transform(ndf.iloc[:,2:].to_numpy())


In [8]:
output_name='CASIA1_features.csv'
ndf.to_csv(output_name, index=False)

In [26]:
new = df.append(ndf, ignore_index=True)
new.reset_index()
new

image_names  label         2         3         4         5  \
0     Au_pla_30322.jpg      0  0.203030  0.114708  0.091051  0.071826   
1     Au_ani_10197.jpg      0  0.153429  0.099287  0.123705  0.130321   
2     Au_nat_00098.jpg      0  0.075379  0.058618  0.055116  0.050434   
3     Au_nat_30407.jpg      0  0.320666  0.322521  0.298455  0.272717   
4     Au_arc_20034.jpg      0  0.298256  0.227842  0.216022  0.196337   
...                ...    ...       ...       ...       ...       ...   
1716   Au_txt_0096.jpg      0       NaN       NaN       NaN       NaN   
1717   Au_txt_0097.jpg      0       NaN       NaN       NaN       NaN   
1718   Au_txt_0098.jpg      0       NaN       NaN       NaN       NaN   
1719   Au_txt_0099.jpg      0       NaN       NaN       NaN       NaN   
1720   Au_txt_0100.jpg      0       NaN       NaN       NaN       NaN   

             6         7         8         9  ...       748       749  \
0     0.061546  0.051228  0.040522  0.381164  ...       NaN       NaN   
1     0.138604  0.127693  0.166308  0.380715  ...       NaN       NaN   
2     0.045391  0.043785  0.042841  0.510323  ...       NaN       NaN   
3     0.269061  0.261953  0.242288  0.416608  ...       NaN       NaN   
4     0.181617  0.196589  0.182347  0.488406  ...       NaN       NaN   
...        ...       ...       ...       ...  ...       ...       ...   
1716       NaN       NaN       NaN       NaN  ...  0.422056  0.480904   
1717       NaN       NaN       NaN       NaN  ...  0.543118  0.539361   
1718       NaN       NaN       NaN       NaN  ...  0.417910  0.477007   
1719       NaN       NaN       NaN       NaN  ...  0.540630  0.632112   
1720       NaN       NaN       NaN       NaN  ...  0.262023  0.312549   

           750       751       752       753       754       755       756  \
0          NaN       NaN       NaN       NaN       NaN       NaN       NaN   
1          NaN       NaN       NaN       NaN       NaN       NaN       NaN   
2          NaN       NaN       NaN       NaN       NaN       NaN       NaN   
3          NaN       NaN       NaN       NaN       NaN       NaN       NaN   
4          NaN       NaN       NaN       NaN       NaN       NaN       NaN   
...        ...       ...       ...       ...       ...       ...       ...   
1716  0.017669  0.398091  0.413878  0.385524  0.300337  0.400253  0.417836   
1717  0.017669  0.408998  0.552653  0.423191  0.607424  0.459151  0.540875   
1718  0.017669  0.423995  0.439184  0.395864  0.429696  0.432552  0.439306   
1719  0.017669  0.439673  0.535510  0.433530  0.525309  0.478784  0.526012   
1720  0.017669  0.292434  0.269388  0.294682  0.105737  0.317923  0.268373   

           757  
0          NaN  
1          NaN  
2          NaN  
3          NaN  
4          NaN  
...        ...  
1716  0.446856  
1717  0.501497  
1718  0.493263  
1719  0.588323  
1720  0.330090  

[14335 rows x 1514 columns]

In [8]:
trainset = df.drop("image_names", axis=1)

In [9]:
array=trainset.values
x_feature=array[:,1:]
y_label=array[:,0].astype('int')
print(x_feature.shape)
print(y_label.shape)

(14335, 756)
(14335,)


In [10]:
x_feature

array([[0.2030304 , 0.11470844, 0.09105144, ..., 0.15390372, 0.12828947,
        0.18026706],
       [0.15342884, 0.0992869 , 0.12370499, ..., 0.21950611, 0.13588057,
        0.16320475],
       [0.07537936, 0.05861842, 0.05511573, ..., 0.08730357, 0.06047571,
        0.10880316],
       ...,
       [0.22904502, 0.21707648, 0.17197567, ..., 0.43255225, 0.43930636,
        0.49326347],
       [0.40616975, 0.4979294 , 0.48371449, ..., 0.47878404, 0.52601156,
        0.58832335],
       [0.4481609 , 0.54358333, 0.57104341, ..., 0.31792274, 0.26837324,
        0.33008982]])

In [11]:
X_train,X_test,Y_train,Y_test=train_test_split(x_feature,y_label,test_size=0.20,random_state=7)

In [12]:
X_train

array([[0.28053323, 0.27715118, 0.26767285, ..., 0.16762285, 0.15460526,
        0.19114738],
       [0.21305225, 0.19484471, 0.20423936, ..., 0.10152158, 0.07135627,
        0.11275964],
       [0.18857999, 0.14335036, 0.14375774, ..., 0.07782489, 0.08147773,
        0.0615727 ],
       ...,
       [0.25852926, 0.20422386, 0.17813738, ..., 0.61486655, 0.58881579,
        0.39070227],
       [0.26715803, 0.23526538, 0.23992976, ..., 0.09753056, 0.10374494,
        0.07739862],
       [0.3292156 , 0.34775   , 0.35261075, ..., 0.12222499, 0.09741903,
        0.10583581]])

In [13]:

model_SVC=svm.SVC(kernel='rbf',C=100,gamma=0.001)

kfold=KFold(n_splits=10, shuffle=True)
cv_results=cross_val_score(model_SVC,X_train,Y_train,cv=kfold,scoring='accuracy')
msg="%s %f (%f)" % ('Training Accuracy: ',cv_results.mean(),cv_results.std())
print(msg)

Training Accuracy:  0.946199 (0.007796)


In [13]:
# SVM hypertuning using GridSeachCV
model_SVC=svm.SVC()

kfold=KFold(n_splits=10)
param_grid = {'C': [1, 10, 100, 500, 1000], 
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
              'kernel': ['rbf']} 

grid=GridSearchCV(estimator=model_SVC,param_grid=param_grid,scoring='accuracy',cv=kfold,verbose=3)
grid_result=grid.fit(X_train,Y_train)

print("Best: %f using %s" % (grid_result.best_score_,grid_result.best_params_))

Fitting 10 folds for each of 25 candidates, totalling 250 fits
[CV 1/10] END .........C=1, gamma=1, kernel=rbf;, score=0.915 total time=  23.9s
[CV 2/10] END .........C=1, gamma=1, kernel=rbf;, score=0.900 total time=  23.6s
[CV 3/10] END .........C=1, gamma=1, kernel=rbf;, score=0.900 total time=  23.6s
[CV 4/10] END .........C=1, gamma=1, kernel=rbf;, score=0.909 total time=  23.8s
[CV 5/10] END .........C=1, gamma=1, kernel=rbf;, score=0.922 total time=  23.9s
[CV 6/10] END .........C=1, gamma=1, kernel=rbf;, score=0.897 total time=  23.7s
[CV 7/10] END .........C=1, gamma=1, kernel=rbf;, score=0.909 total time=  23.8s
[CV 8/10] END .........C=1, gamma=1, kernel=rbf;, score=0.909 total time=  25.4s
[CV 9/10] END .........C=1, gamma=1, kernel=rbf;, score=0.917 total time=  25.8s
[CV 10/10] END ........C=1, gamma=1, kernel=rbf;, score=0.914 total time=  24.6s
[CV 1/10] END .......C=1, gamma=0.1, kernel=rbf;, score=0.958 total time=  15.4s
[CV 2/10] END .......C=1, gamma=0.1, kernel=rb

[CV 2/10] END .......C=100, gamma=1, kernel=rbf;, score=0.905 total time=  17.4s
[CV 3/10] END .......C=100, gamma=1, kernel=rbf;, score=0.911 total time=  17.5s
[CV 4/10] END .......C=100, gamma=1, kernel=rbf;, score=0.920 total time=  17.4s
[CV 5/10] END .......C=100, gamma=1, kernel=rbf;, score=0.930 total time=  17.4s
[CV 6/10] END .......C=100, gamma=1, kernel=rbf;, score=0.901 total time=  17.2s
[CV 7/10] END .......C=100, gamma=1, kernel=rbf;, score=0.908 total time=  17.1s
[CV 8/10] END .......C=100, gamma=1, kernel=rbf;, score=0.906 total time=  17.5s
[CV 9/10] END .......C=100, gamma=1, kernel=rbf;, score=0.917 total time=  17.1s
[CV 10/10] END ......C=100, gamma=1, kernel=rbf;, score=0.910 total time=  17.4s
[CV 1/10] END .....C=100, gamma=0.1, kernel=rbf;, score=0.967 total time=   7.4s
[CV 2/10] END .....C=100, gamma=0.1, kernel=rbf;, score=0.959 total time=   7.8s
[CV 3/10] END .....C=100, gamma=0.1, kernel=rbf;, score=0.956 total time=   7.4s
[CV 4/10] END .....C=100, ga

[CV 4/10] END ......C=1000, gamma=1, kernel=rbf;, score=0.917 total time=  17.0s
[CV 5/10] END ......C=1000, gamma=1, kernel=rbf;, score=0.929 total time=  17.0s
[CV 6/10] END ......C=1000, gamma=1, kernel=rbf;, score=0.904 total time=  17.0s
[CV 7/10] END ......C=1000, gamma=1, kernel=rbf;, score=0.902 total time=  16.8s
[CV 8/10] END ......C=1000, gamma=1, kernel=rbf;, score=0.905 total time=  16.8s
[CV 9/10] END ......C=1000, gamma=1, kernel=rbf;, score=0.912 total time=  16.9s
[CV 10/10] END .....C=1000, gamma=1, kernel=rbf;, score=0.907 total time=  17.2s
[CV 1/10] END ....C=1000, gamma=0.1, kernel=rbf;, score=0.955 total time=   6.8s
[CV 2/10] END ....C=1000, gamma=0.1, kernel=rbf;, score=0.949 total time=   6.7s
[CV 3/10] END ....C=1000, gamma=0.1, kernel=rbf;, score=0.950 total time=   6.9s
[CV 4/10] END ....C=1000, gamma=0.1, kernel=rbf;, score=0.959 total time=   6.9s
[CV 5/10] END ....C=1000, gamma=0.1, kernel=rbf;, score=0.965 total time=   7.0s
[CV 6/10] END ....C=1000, ga

In [14]:
model_SVC = svm.SVC(C=500,gamma=0.01, kernel='rbf')
model_SVC.fit(X_train,Y_train) 

predictions=model_SVC.predict(X_test)

print(accuracy_score(Y_test,predictions))
print(confusion_matrix(Y_test,predictions))
print(classification_report(Y_test,predictions))

0.9703522846180677
[[1598   64]
 [  21 1184]]
              precision    recall  f1-score   support

           0       0.99      0.96      0.97      1662
           1       0.95      0.98      0.97      1205

    accuracy                           0.97      2867
   macro avg       0.97      0.97      0.97      2867
weighted avg       0.97      0.97      0.97      2867



In [15]:
newpicst = "/Users/andre/Desktop/conda/grad/TP2"
newpicsa = "/Users/andre/Desktop/conda/grad/AU1"

In [17]:
newimt = feature_extraction(newpicst,1)
newima = feature_extraction(newpicsa,0)

In [ ]:
ndf=pd.read_csv('/Users/andre/Desktop/conda/grad/CASIA1_features.csv')

In [18]:
ndf = pd.DataFrame(newimt)
ndf = ndf.append(pd.DataFrame(newima), ignore_index=True)

In [19]:
ndf.rename(columns = {0: "image_names", 1: "label"}, inplace = True)
ndf

image_names  label           2           3  \
0                     IMG-20221227-WA0005.jpg      1   38.911957   16.765043   
1                     IMG-20221227-WA0006.jpg      1   97.736536   44.515916   
2                     IMG-20221227-WA0007.jpg      1   96.319536   62.205731   
3                     IMG-20221227-WA0008.jpg      1   54.224094   28.502323   
4                     IMG-20221227-WA0009.jpg      1  112.196142   64.840849   
5                     IMG-20221227-WA0010.jpg      1   94.222711   43.317604   
6                     IMG-20221227-WA0011.jpg      1   81.678570   38.362623   
7                     IMG-20221227-WA0012.jpg      1   60.577699   39.242977   
8                     IMG-20221227-WA0013.jpg      1  105.146130   58.874346   
9                     IMG-20221227-WA0014.jpg      1   93.474098   37.306070   
10                    IMG-20221227-WA0015.jpg      1   77.637870   38.801372   
11                    IMG-20221227-WA0016.jpg      1  123.396797   57.046007   
12                    IMG-20221227-WA0017.jpg      1   92.181055   41.761669   
13                    IMG-20221227-WA0018.jpg      1   73.682020   30.541818   
14                    IMG-20221225-WA0020.jpg      0  153.880413  100.056286   
15                    IMG-20221225-WA0021.jpg      0  205.284731  140.518233   
16                    IMG-20221225-WA0022.jpg      0  218.609877  156.973083   
17                    IMG-20221225-WA0023.jpg      0  158.993459  104.640569   
18                    IMG-20221225-WA0024.jpg      0  165.201021   96.937866   
19                    IMG-20221225-WA0025.jpg      0  221.951149  144.002948   
20                    IMG-20221225-WA0026.jpg      0  124.359780   64.551559   
21                    IMG-20221225-WA0027.jpg      0  113.776019   63.863035   
22                    IMG-20221225-WA0028.jpg      0  161.364825  101.553545   
23                    IMG-20221225-WA0029.jpg      0  132.596397   78.581502   
24                    IMG-20221225-WA0030.jpg      0  146.857076   82.634851   
25                    IMG-20221225-WA0031.jpg      0  154.556584   72.930746   
26                    IMG-20221225-WA0032.jpg      0  135.659900   89.243930   
27                    IMG-20221225-WA0033.jpg      0  153.923018   76.185906   
28  WhatsApp Image 2022-12-25 at 11.34.02.jpg      0  173.735332  125.021683   

             4           5          6          7          8            9  ...  \
0    13.368419   11.749223   4.636841   3.150059   2.240882   603.136192  ...   
1    29.830560   23.716125  15.108461  10.965616   8.421250   936.242326  ...   
2    46.072099   36.326072  21.511189  10.580042   5.773477   636.511367  ...   
3    22.263876   16.088467   9.036193   6.537947   4.322591   708.685120  ...   
4    44.610874   30.770790  18.351991   9.994310   4.630016   606.053022  ...   
5    22.843536   17.738706  10.957244  10.321636   9.141439  1266.505886  ...   
6    21.829407   15.610875  10.192574   6.535511   5.421925  1023.192287  ...   
7    29.506410   19.599184  12.398630   7.318635   4.685373   623.205664  ...   
8    36.537279   23.891657  14.367548   7.384969   4.189140   752.000627  ...   
9    22.907930   14.620706   9.295993   7.180328   6.481602  1061.939740  ...   
10   20.660087   12.995686   8.128572   6.462084   5.936218   625.577058  ...   
11   30.719911   18.529109  12.430358  10.523190   7.288321   963.348020  ...   
12   26.381155   20.548691  11.769071   7.854061   6.267621  1211.574799  ...   
13   17.121814   12.090706   7.176798   5.424372   4.168554  1057.907454  ...   
14   87.300787   62.744934  47.819053  33.751837  19.808822   717.580012  ...   
15  118.599434  106.949892  82.911693  59.821812  52.793972   842.923321  ...   
16  111.385853   88.118420  74.521433  46.086710  34.260226   755.396979  ...   
17   73.966019   54.241682  42.242436  33.131064  19.056931   923.532231  ...   
18   73.342692   60.244519  48.885547  35.822264  27.171077   816.896795  ...   
19  100.36268

In [20]:
ndf.drop(columns = ndf.columns[0], axis = 1, inplace= True)
ndf

label           2           3           4           5          6  \
0       1   38.911957   16.765043   13.368419   11.749223   4.636841   
1       1   97.736536   44.515916   29.830560   23.716125  15.108461   
2       1   96.319536   62.205731   46.072099   36.326072  21.511189   
3       1   54.224094   28.502323   22.263876   16.088467   9.036193   
4       1  112.196142   64.840849   44.610874   30.770790  18.351991   
5       1   94.222711   43.317604   22.843536   17.738706  10.957244   
6       1   81.678570   38.362623   21.829407   15.610875  10.192574   
7       1   60.577699   39.242977   29.506410   19.599184  12.398630   
8       1  105.146130   58.874346   36.537279   23.891657  14.367548   
9       1   93.474098   37.306070   22.907930   14.620706   9.295993   
10      1   77.637870   38.801372   20.660087   12.995686   8.128572   
11      1  123.396797   57.046007   30.719911   18.529109  12.430358   
12      1   92.181055   41.761669   26.381155   20.548691  11.769071   
13      1   73.682020   30.541818   17.121814   12.090706   7.176798   
14      0  153.880413  100.056286   87.300787   62.744934  47.819053   
15      0  205.284731  140.518233  118.599434  106.949892  82.911693   
16      0  218.609877  156.973083  111.385853   88.118420  74.521433   
17      0  158.993459  104.640569   73.966019   54.241682  42.242436   
18      0  165.201021   96.937866   73.342692   60.244519  48.885547   
19      0  221.951149  144.002948  100.362686   70.952807  51.878953   
20      0  124.359780   64.551559   42.365628   29.837944  23.316354   
21      0  113.776019   63.863035   37.750908   24.156954  18.497075   
22      0  161.364825  101.553545   67.133836   46.704834  33.058273   
23      0  132.596397   78.581502   62.598029   53.447162  38.346262   
24      0  146.857076   82.634851   51.631772   41.454486  33.210007   
25      0  154.556584   72.930746   55.921944   43.521738  33.416391   
26      0  135.659900   89.243930   62.509585   40.433922  27.777592   
27      0  153.923018   76.185906   55.705056   46.608648  31.901021   
28      0  173.735332  125.021683   95.784588   78.144482  58.789681   

            7          8            9          10  ...     748     749  \
0    3.150059   2.240882   603.136192   39.515967  ...   510.0  1582.0   
1   10.965616   8.421250   936.242326   97.812302  ...  1133.0  2147.0   
2   10.580042   5.773477   636.511367   94.146570  ...  1045.0  2215.0   
3    6.537947   4.322591   708.685120   50.848855  ...   767.0  2139.0   
4    9.994310   4.630016   606.053022  111.732527  ...  1746.0  3023.0   
5   10.321636   9.141439  1266.505886   95.532885  ...   574.0  1742.0   
6    6.535511   5.421925  1023.192287   80.272459  ...   992.0  2273.0   
7    7.318635   4.685373   623.205664   58.804506  ...   866.0  2162.0   
8    7.384969   4.189140   752.000627  104.421292  ...  1461.0  2912.0   
9    7.180328   6.481602  1061.939740   92.841984  ...  1113.0  2236.0   
10   6.462084   5.936218   625.577058   77.973335  ...  1339.0  2791.0   
11  10.523190   7.288321   963.348020  124.265573  ...   925.0  1661.0   
12   7.854061   6.267621  1211.574799   91.365564  ...   911.0  1993.0   
13   5.424372   4.168554  1057.907454   73.039883  ...   556.0  1569.0   
14  33.751837  19.808822   717.580012  152.816347  ...   294.0   487.0   
15  59.821812  52.793972   842.923321  203.815148  ...   520.0   769.0   
16  46.086710  34.260226   755.396979  219.172841  ...   824.0  1184.0   
17  33.131064  19.056931   923.532231  154.083722  ...   868.0  1294.0   
18  35.822264  27.171077   816.896795  163.876290  ...  2351.0  3736.0   
19  36.206253  32.823263   974.780955  220.651345  ...   349.0   524.0   
20  14.277650  10.790123   834.982772  122.454557  ...   693.0  1084.0   
21  18.459888  16.097995  1067.962295  113.339180  ...  1787.0  3844.0   
22  27.566577  22.850509   835.677410  164.800972  ...   394.0   591.0   
23  26.739785  22.987337   792.115595  129.759033  ...   231.0   38

In [21]:
scaler_norm = MinMaxScaler(feature_range=(0, 1),copy=True, clip=True) 
ndf.iloc[:,1:] = scaler_norm.fit_transform(ndf.iloc[:,1:].to_numpy()) # Normalising the values in dataframe.
ndf

label         2         3         4         5         6         7  \
0       1  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
1       1  0.321377  0.197926  0.156438  0.125702  0.133780  0.137909   
2       1  0.313635  0.324095  0.310780  0.258158  0.215578  0.131106   
3       1  0.083655  0.083713  0.084533  0.045580  0.056204  0.059781   
4       1  0.400374  0.342889  0.296894  0.199805  0.175218  0.120770   
5       1  0.302180  0.189380  0.090041  0.062914  0.080746  0.126546   
6       1  0.233647  0.154040  0.080404  0.040563  0.070977  0.059738   
7       1  0.118367  0.160318  0.153358  0.082457  0.099161  0.073556   
8       1  0.361858  0.300334  0.220171  0.127546  0.124315  0.074727   
9       1  0.298090  0.146504  0.090653  0.030162  0.059523  0.071116   
10      1  0.211572  0.157169  0.069292  0.013093  0.044609  0.058442   
11      1  0.461567  0.287294  0.164890  0.071217  0.099566  0.130102   
12      1  0.291026  0.178282  0.123659  0.092431  0.091118  0.083004   
13      1  0.189960  0.098260  0.035668  0.003587  0.032449  0.040131   
14      0  0.628108  0.594055  0.702572  0.535665  0.551674  0.539983   
15      0  0.908946  0.882640  1.000000  1.000000  1.000000  1.000000   
16      0  0.981746  1.000000  0.931450  0.802192  0.892810  0.757638   
17      0  0.656043  0.626751  0.575853  0.446346  0.480430  0.529029   
18      0  0.689956  0.571813  0.569930  0.509401  0.565299  0.576517   
19      0  1.000000  0.907494  0.826698  0.621882  0.603541  0.583292   
20      0  0.466828  0.340826  0.275558  0.190006  0.238640  0.196352   
21      0  0.409006  0.335915  0.231704  0.130332  0.177071  0.270149   
22      0  0.668998  0.604734  0.510927  0.367178  0.363098  0.430841   
23      0  0.511827  0.440891  0.467824  0.438000  0.430655  0.416252   
24      0  0.589738  0.469801  0.363613  0.312028  0.365036  0.500144   
25      0  0.631803  0.400588  0.404382  0.333743  0.367673  0.394675   
26      0  0.528564  0.516938  0.466984  0.301308  0.295635  0.222190   
27      0  0.628341  0.423805  0.402321  0.366168  0.348313  0.408076   
28      0  0.736582  0.772114  0.783193  0.697424  0.691829  0.736267   

           8         9        10  ...       748       749       750       751  \
0   0.000000  0.000000  0.000000  ...  0.045213  0.249948  0.312862  0.154197   
1   0.122255  0.502143  0.321838  ...  0.145455  0.368025  0.312862  0.210245   
2   0.069879  0.050312  0.301601  ...  0.131295  0.382236  0.312862  0.203858   
3   0.041179  0.159110  0.062566  ...  0.086565  0.366353  0.312862  0.188347   
4   0.047260  0.004397  0.398688  ...  0.244087  0.551097  0.312862  0.281152   
5   0.136501  1.000000  0.309254  ...  0.055511  0.283386  0.312862  0.135688   
6   0.062925  0.633216  0.225006  ...  0.122767  0.394357  0.312862  0.202033   
7   0.048355  0.030254  0.106487  ...  0.102494  0.371160  0.312862  0.195255   
8   0.038539  0.224406  0.358325  ...  0.198230  0.527900  0.312862  0.246090   
9   0.083886  0.691626  0.294399  ...  0.142237  0.386625  0.312862  0.204119   
10  0.073098  0.033829  0.212313  ...  0.178600  0.502612  0.312862  0.246611   
11  0.099844  0.543003  0.467880  ...  0.111987  0.266458  0.312862  0.133603   
12  0.079654  0.917194  0.286248  ...  0.109735  0.335841  0.312862  0.172185   
13  0.038132  0.685547  0.185077  ...  0.052615  0.247231  0.312862  0.120829   
14  0.347515  0.172519  0.625501  ...  0.010459  0.021108  0.000000  0.001043   
15  1.000000  0.361468  0.907052  ...  0.046822  0.080042  0.038085  0.042492   
16  0.633381  0.229526  0.991838  ...  0.095736  0.166771  0.056737  0.079771   
17  0.332641  0.482983  0.632498  ...  0.102816  0.189760  0.098385  0.095933   
18  0.493149  0.322235  0.686560  ...  0.341432  0.700104  0.354399  0.316606   
19  0.604956  0.560238  1.000000  ...  0.019308  0.028840  0.000000  0.011992   
20  0.169114  0.349498  0.457882  ...  0.074658  0.145873  0.111359  0.078858   
21  0.274110  0.700704  0.40755

In [22]:
array=ndf.values
tx_feature=array[:,1:]
ty_label=array[:,0].astype('int')
print(tx_feature.shape)
print(ty_label.shape)

(29, 756)
(29,)


In [23]:
tx_feature

array([[0.        , 0.        , 0.        , ..., 0.15987038, 0.0518975 ,
        0.27257933],
       [0.32137696, 0.1979264 , 0.15643811, ..., 0.22198218, 0.15553033,
        0.37774614],
       [0.31363545, 0.32409474, 0.31077986, ..., 0.23035377, 0.14044762,
        0.38364524],
       ...,
       [0.52856409, 0.51693817, 0.46698368, ..., 0.00324062, 0.        ,
        0.01688365],
       [0.62834118, 0.42380497, 0.4023209 , ..., 0.0305158 , 0.01459617,
        0.06143206],
       [0.73658201, 0.77211436, 0.78319276, ..., 1.        , 1.        ,
        1.        ]])

In [24]:
ty_label

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0])

In [25]:
test_predictions=model_SVC.predict(tx_feature)

In [26]:
test_predictions

array([0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 0])

In [27]:
print(accuracy_score(ty_label,test_predictions))
print(confusion_matrix(ty_label,test_predictions))
print(classification_report(ty_label,test_predictions))

0.3793103448275862
[[ 4 11]
 [ 7  7]]
              precision    recall  f1-score   support

           0       0.36      0.27      0.31        15
           1       0.39      0.50      0.44        14

    accuracy                           0.38        29
   macro avg       0.38      0.38      0.37        29
weighted avg       0.38      0.38      0.37        29

